name: simply_music
description: "A simple music app."
publish_to: 'none'
version: 1.0.2+1
environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  youtube_explode_dart: ^2.3.6
  path: ^1.9.0
  path_provider: ^2.1.5
  on_audio_query: ^2.9.0
  audioplayers: ^6.1.0
  just_audio: ^0.9.43
  just_audio_background: ^0.0.1-beta.14
  permission_handler: ^11.3.1
  ffmpeg_kit_flutter: ^6.0.3
  sqflite: ^2.4.1
  flutter_slidable: ^4.0.0
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

