name: music_magic
description: "A simple music app."
publish_to: 'none'
version: 1.0.2+1
environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  youtube_explode_dart: ^2.3.6
  path: ^1.9.0
  path_provider: ^2.1.5
  on_audio_query: ^2.9.0
  on_audio_query_android_v1_8: ^1.1.1
  audioplayers: ^6.1.0
  just_audio: ^0.9.43
  just_audio_background: ^0.0.1-beta.14
  permission_handler: ^11.3.1
  ffmpeg_kit_flutter: ^6.0.3
  sqflite: ^2.4.1
  flutter_slidable: ^4.0.0
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  share_plus: ^10.1.4
  marquee: ^2.3.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/SimplyMusic_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/download_page.png
    - assets/images/SimplyMusic_logo.png
    - assets/images/title_page.png
    - assets/images/music_page.png
    - assets/images/dark_palm_page.png
    - assets/images/delete_ex.png
    - assets/images/edit_ex.png
    - assets/images/music_player_page.png


  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-SemiBold.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf
          style: italic
